import { LocationData } from './types';
import { US_STATES } from './constants';

export function cn(...classes: string[]) {
  return classes.filter(Boolean).join(' ');
}

export async function getCurrentLocation(): Promise<LocationData | null> {
  return new Promise((resolve) => {
    if (!navigator.geolocation) {
      resolve(null);
      return;
    }

    navigator.geolocation.getCurrentPosition(
      async (position) => {
        const { latitude, longitude } = position.coords;
        
        try {
          // Use reverse geocoding to get state information
          const response = await fetch(
            `https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${latitude}&longitude=${longitude}&localityLanguage=en`
          );
          
          if (response.ok) {
            const data = await response.json();
            const state = data.principalSubdivision || '';
            const city = data.city || '';
            
            // Convert full state name to abbreviation
            const stateCode = US_STATES[state as keyof typeof US_STATES] || state;
            
            resolve({
              latitude,
              longitude,
              state: stateCode,
              city
            });
          } else {
            resolve({
              latitude,
              longitude,
              state: 'CA' // Default fallback
            });
          }
        } catch (error) {
          console.error('Geocoding error:', error);
          resolve({
            latitude,
            longitude,
            state: 'CA' // Default fallback
          });
        }
      },
      (error) => {
        console.error('Geolocation error:', error);
        resolve(null);
      },
      {
        enableHighAccuracy: true,
        timeout: 10000,
        maximumAge: 300000 // 5 minutes
      }
    );
  });
}

export function formatDuration(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return `${mins}:${secs.toString().padStart(2, '0')}`;
}

export function formatTimestamp(timestamp: number): string {
  return new Date(timestamp).toLocaleString();
}

export function generateShareableText(
  state: string,
  location: string,
  timestamp: number,
  keyRights: string[]
): string {
  const date = new Date(timestamp).toLocaleDateString();
  const time = new Date(timestamp).toLocaleTimeString();
  
  return `Know Your Rights Card - ${state}
Date: ${date} at ${time}
Location: ${location}

Key Rights:
${keyRights.map(right => `• ${right}`).join('\n')}

Generated by Know Your Rights Card App`;
}

export async function requestMediaPermissions(): Promise<boolean> {
  try {
    const stream = await navigator.mediaDevices.getUserMedia({ 
      audio: true, 
      video: false 
    });
    
    // Stop the stream immediately as we just needed permission
    stream.getTracks().forEach(track => track.stop());
    return true;
  } catch (error) {
    console.error('Media permission denied:', error);
    return false;
  }
}

export function saveToLocalStorage(key: string, data: any): void {
  try {
    localStorage.setItem(key, JSON.stringify(data));
  } catch (error) {
    console.error('Failed to save to localStorage:', error);
  }
}

export function loadFromLocalStorage<T>(key: string, defaultValue: T): T {
  try {
    const item = localStorage.getItem(key);
    return item ? JSON.parse(item) : defaultValue;
  } catch (error) {
    console.error('Failed to load from localStorage:', error);
    return defaultValue;
  }
}
